version: "3.8"
services:
  mymongodb:
    image: mongo:latest
    container_name: mymongodb
    ports:
      - 27017:27017

  springboot-mongo:
    build: .
    container_name: springboot-mongodb
    ports:
      - 8070:8080
    links:
      - mymongodb